name: feature-pipeline
on:  [push]

jobs:
  feature-pipeline:
    uses: 70-git/common-workflows/.github/workflows/nodejs-featurepipeline.yml@main
    with:
      environment: dev
      project: roboshop
      component: frontend
