name: main-workflow
on: [push]
concurrency:
    group: ${{ github.workflow }}-$ {{ github.ref_name }}
    cancel-in-progress: true # if present execution will be cancelled, new trigeer will happen
jobs:
  sampleworkflow:
    runs-on: ubuntu-latest
    steps:
      - name: "sample0123"
        run: sleep 60
        