name: secrets-demo
on:
  push:
jobs:
  secrets-demo:
    runs-on: ubuntu-latest
    steps:
      - name: "print info"
        run: |
         echo "demo-purpose: ${{ secrets.DB_SECRET }}"
         echo "demo-purpose: ${{ vars.DB_URL }}"