name: secrets-demo
on:
  push:
jobs:
  secrets-demo:
    runs-on: ubuntu-latest
    steps:
      - name: "print info"
        run: |
         echo "demo-purpose: ${{ secrets.DB_SECRET }}"
         echo "demo-purpose: ${{ vars.DB_URL }}"


      - name: "out_put values"
        id: tag
        run: |
         echo "version= 1.0.0" >>$GITHUB_OUTPUT
         echo "Image_name=catalogue" >> $GITHUB_OUTPUT


      - name: "Access the outputs previous steps"
        run: |
         echo "version: ${{ steps.tag.outputs.version}}"
         echo "image_name: ${{ steps.tag.outputs.Image_name}}"

      - name: "github_env"
        run: |
          echo "course:github-actions" >> $GITHUB_OUTPUT
          echo "Duration:10" >> $GITHUB_OUTPUT  

      - name: "Access the env variables"
        run: | 
         echo "course: $course"
         echo "Duration: $Duration"     
